// <auto-generated />
namespace Examen_Practico_CodeFirst_RaulGonzalez_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Seed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed2));
        
        string IMigrationMetadata.Id
        {
            get { return "202411081854319_Seed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
